### ISSUE TITLE
Somthing about the retrieval evaluator

### ISSUE THREAD

**Issue by leaf-ygq** [HuskyInSalt/CRAG#4]
In the paper, the article retrieval evaluator uses fine-tuned model T5-large. What is the size of the fine-tuning data set and how is it constructed? Can you provide the fine-tuning dataset and corresponding training code?

**Comment by HuskyInSalt** [comment]
Hi @leaf-ygq ! In the experiments, we fine-tuned the evaluator on the PopQA training set, you can see our response in #1  for more details. And our training code will be released sooner.
