### ISSUE TITLE
Issues about the overall code

### ISSUE THREAD

**Issue by QiyiJiang** [HuskyInSalt/CRAG#5]
Hello, I carefully studied the code you released. I would like to ask if this code is the implementation of your paper “Corrective Retrieval Augmented Generation”? Why does the logic of the code feel mismatched with the paper?

**Comment by HuskyInSalt** [comment]
This repo contains the exact implementation code of our paper. You can easily reproduce the whole framework illustrated in our paper by following the friendly-to-understanding instructions in the readme.
